_BASE_: "../ade20k/semantic-segmentation/maskformer2_R50_bs16_160k.yaml"
MODEL:
  WEIGHTS: "weights/ade20k_semantic_R50.pkl"
  SEM_SEG_HEAD:
    NUM_CLASSES: 4 # Background + Cervical, Thoracic, Lumbar
DATASETS:
  TRAIN: ("verse_semantic_train",)
  TEST: ("verse_semantic_val",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  MAX_ITER: 20000 # Medical datasets are smaller; 20k-40k is usually enough
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "./output/verse_semantic_R50"
