_BASE_: "../ade20k/panoptic-segmentation/maskformer2_R50_bs16_160k.yaml"
MODEL:
  WEIGHTS: "weights/ade20k_panoptic_R50.pkl"
  SEM_SEG_HEAD:
    NUM_CLASSES: 29 # 28 Vertebrae + 1 Background
DATASETS:
  TRAIN: ("verse_panoptic_train",)
  TEST: ("verse_panoptic_val",)
  VERSE_ROOT: "../dataset_verse_2d/ade20k"
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  MAX_ITER: 20000
OUTPUT_DIR: "./output/verse_panoptic_R50"
