_BASE_: "../ade20k/instance-segmentation/maskformer2_R50_bs16_160k.yaml"
MODEL:
  WEIGHTS: "weights/ade20k_instance_R50.pkl"
  SEM_SEG_HEAD:
    NUM_CLASSES: 28 # All 28 vertebrae as separate "Things"
DATASETS:
  TRAIN: ("verse_instance_train",)
  TEST: ("verse_instance_val",)
  VERSE_ROOT: "../dataset_verse_2d/ade20k"
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  MAX_ITER: 20000 # Medical datasets are smaller; 20k-40k is usually enough
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "./output/verse_ade20k_instance_R50"
